# Generated by Django 4.2.1 on 2023-06-23 22:41

from django.db import migrations, models
import modelcluster.contrib.taggit
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('business_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(default='', help_text="The business's address", max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_name',
            field=models.TextField(blank=True, help_text="The name of the business's contact", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='The description of the business', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='fax_number',
            field=models.TextField(blank=True, help_text="The business's fax number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.TextField(default='', help_text='The name of the business', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.TextField(blank=True, help_text="The business's phone number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.TextField(blank=True, help_text="The business's website", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of categories', through='business_directory.Category', to='taggit.Tag', verbose_name='Categories'),
        ),
    ]
