# Generated by Django 4.2.4 on 2023-08-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtaildocs.document')),
                ('transcription', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtaildocs.document', models.Model),
        ),
    ]
