# Generated by Django 4.2.3 on 2023-12-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchable_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, help_text='The date associated with the document.', null=True, verbose_name='date'),
        ),
    ]
