# Generated by Django 4.2.1 on 2023-07-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='alignment',
            field=models.IntegerField(blank=True, choices=[(0, 'Left'), (1, 'Center'), (2, 'Right')], default=0),
        ),
    ]
