# Generated by Django 4.2.1 on 2023-06-24 00:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business_directory', '0002_business_address_business_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='business_directory.business'),
        ),
    ]
