# Generated by Django 4.2.3 on 2023-07-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basepage',),
        ),
        migrations.CreateModel(
            name='RedirectorPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basepage')),
                ('redirect_to', models.URLField(help_text='The URL to redirect to')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basepage',),
        ),
    ]
