# Generated by Django 4.2.1 on 2023-07-11 23:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menuitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
