# Generated by Django 4.2.3 on 2023-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='The time when the air quality measurement was taken', null=True)),
                ('current', models.FloatField()),
                ('avg_10minute', models.FloatField()),
                ('avg_30minute', models.FloatField()),
                ('avg_60minute', models.FloatField()),
                ('avg_6hour', models.FloatField()),
                ('avg_24hour', models.FloatField()),
                ('avg_week', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day when the forecasted weather occurs', null=True)),
                ('main', models.CharField(help_text='The type of weather (rain, snow, etc.)', max_length=20)),
                ('description', models.CharField(help_text='A description of the weather', max_length=30)),
                ('icon_id', models.CharField(help_text='The id of the icon', max_length=3)),
                ('forecast_index', models.IntegerField()),
                ('high_temperature', models.IntegerField(null=True)),
                ('low_temperature', models.IntegerField(null=True)),
                ('current_temperature', models.IntegerField(null=True)),
            ],
        ),
    ]
