# Generated by Django 4.2.3 on 2023-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day when the forecasted weather occurs')),
                ('main', models.CharField(help_text='The type of weather (rain, snow, etc.)', max_length=20)),
                ('description', models.CharField(help_text='A description of the weather', max_length=30)),
                ('icon_id', models.CharField(help_text='The id of the icon', max_length=3)),
                ('high_temperature', models.FloatField()),
                ('low_temperature', models.FloatField()),
                ('current_temperature', models.FloatField(null=True)),
            ],
        ),
    ]
