# Generated by Django 4.2.3 on 2023-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='forecast_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(help_text='The day when the forecasted weather occurs', null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='high_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='low_temperature',
            field=models.FloatField(null=True),
        ),
    ]
