# Generated by Django 4.2.3 on 2023-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_forecast_forecast_index_alter_forecast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='The time when the air quality measurement was taken', null=True)),
                ('current', models.FloatField()),
                ('avg_10minute', models.FloatField()),
                ('avg_30minute', models.FloatField()),
                ('avg_60minute', models.FloatField()),
                ('avg_6hour', models.FloatField()),
                ('avg_24hour', models.FloatField()),
                ('avg_week', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='current_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='high_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='low_temperature',
            field=models.IntegerField(null=True),
        ),
    ]
