# Generated by Django 4.2.1 on 2023-06-23 22:37

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_singleevent_remove_onetimeevent_eventbase_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbase',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='The description of the event', null=True),
        ),
    ]
