# Generated by Django 4.2.3 on 2023-08-01 22:57

import django.contrib.postgres.fields
from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('business_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='search_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='A list of keywords for the business. These terms will be used when performing searches.', size=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of categories. Businesses will be listed under these keywords on the directory page.', through='business_directory.Category', to='taggit.Tag', verbose_name='Categories'),
        ),
    ]
