# Generated by Django 4.2.4 on 2023-08-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_directory', '0002_business_search_keywords_alter_business_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email_address',
            field=models.TextField(blank=True, default='', help_text="The business's email address", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='google_maps_link',
            field=models.TextField(blank=True, default='', help_text='A link to the business on Google Maps', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='mailing_address',
            field=models.TextField(blank=True, default='', help_text="The business's mailing address", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, default='', help_text="The business's address", max_length=50, null=True),
        ),
    ]
