# Generated by Django 4.2.3 on 2023-07-26 07:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basepage')),
                ('contacts', wagtail.fields.StreamField([('contacts', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Enter the name of the profile', required=True)), ('position', wagtail.blocks.RichTextBlock(help_text='Enter the position of the profile', required=True)), ('email', wagtail.blocks.EmailBlock(help_text='Enter the email of the profile', required=True)), ('phone', wagtail.blocks.CharBlock(help_text='Enter the location of the profile', required=True))]))], blank=True, help_text='Add contacts here', use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basepage',),
        ),
    ]
