# Generated by Django 4.2.1 on 2023-05-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('redirect_to', models.URLField(help_text='The URL to redirect to')),
            ],
            options={
                'verbose_name': 'Redirector',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_background_image',
            field=models.ForeignKey(help_text='The banner background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button1_link',
            field=models.ForeignKey(help_text='Link for first button on the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button1_text',
            field=models.CharField(default='Why Move', help_text='Text for first button on the banner', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button2_link',
            field=models.ForeignKey(help_text='Link for second button on the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button2_text',
            field=models.CharField(default='Open a Business', help_text='Text for second button on the banner', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button3_link',
            field=models.ForeignKey(help_text='Third button on the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button3_text',
            field=models.CharField(default='Job Board', help_text='Text for third button on the banner', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='Text under the banner title', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, help_text='The banner title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_button_text',
            field=models.CharField(default='Businesses', help_text='Text for the businesses button', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item1_image',
            field=models.ForeignKey(help_text='Image for first large businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item1_link',
            field=models.ForeignKey(help_text='Link for first large businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item1_subtext',
            field=models.CharField(default='', help_text='Subtext for first large businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item1_text',
            field=models.CharField(default='', help_text='Text for first large businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item2_image',
            field=models.ForeignKey(help_text='Image for second large businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item2_link',
            field=models.ForeignKey(help_text='Link for second large businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item2_subtext',
            field=models.CharField(default='', help_text='Subtext for second large businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_large_item2_text',
            field=models.CharField(default='', help_text='Text for second large businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item1_icon',
            field=models.CharField(default='', help_text='Icon for first small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item1_link',
            field=models.ForeignKey(help_text='Link for first small businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item1_text',
            field=models.CharField(default='', help_text='Text for first small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item2_icon',
            field=models.CharField(default='', help_text='Icon for second small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item2_link',
            field=models.ForeignKey(help_text='Link for second small businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item2_text',
            field=models.CharField(default='', help_text='Text for second small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item3_icon',
            field=models.CharField(default='', help_text='Icon for third small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item3_link',
            field=models.ForeignKey(help_text='Link for third small businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item3_text',
            field=models.CharField(default='', help_text='Text for third small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item4_icon',
            field=models.CharField(default='', help_text='Icon for fourth small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item4_link',
            field=models.ForeignKey(help_text='Link for fourth small businesses item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='businesses_small_item4_text',
            field=models.CharField(default='', help_text='Text for fourth small businesses item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='information_title',
            field=models.CharField(default='Information', help_text='Information section title text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item1_icon',
            field=models.CharField(default='', help_text='Icon for first popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item1_link',
            field=models.ForeignKey(help_text='Link for first popular page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item1_text',
            field=models.CharField(default='', help_text='Text for first popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item2_icon',
            field=models.CharField(default='', help_text='Icon for second popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item2_link',
            field=models.ForeignKey(help_text='Link for second popular page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item2_text',
            field=models.CharField(default='', help_text='Text for second popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item3_icon',
            field=models.CharField(default='', help_text='Icon for third popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item3_link',
            field=models.ForeignKey(help_text='Link for third popular page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item3_text',
            field=models.CharField(default='', help_text='Text for third popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item4_icon',
            field=models.CharField(default='', help_text='Icon for fourth popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item4_link',
            field=models.ForeignKey(help_text='Link for fourth popular page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_item4_text',
            field=models.CharField(default='', help_text='Text for fourth popular page', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_pages_title',
            field=models.CharField(default='Popular Pages', help_text='Popular pages section title text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_button_text',
            field=models.CharField(default='Residents', help_text='Text for the residents button', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item1_image',
            field=models.ForeignKey(help_text='Image for first large residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item1_link',
            field=models.ForeignKey(help_text='Link for first large residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item1_subtext',
            field=models.CharField(default='', help_text='Subtext for first large residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item1_text',
            field=models.CharField(default='', help_text='Text for first large residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item2_image',
            field=models.ForeignKey(help_text='Image for second large residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item2_link',
            field=models.ForeignKey(help_text='Link for second large residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item2_subtext',
            field=models.CharField(default='', help_text='Subtext for second large residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_large_item2_text',
            field=models.CharField(default='', help_text='Text for second large residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item1_icon',
            field=models.CharField(default='', help_text='Icon for first small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item1_link',
            field=models.ForeignKey(help_text='Link for first small residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item1_text',
            field=models.CharField(default='', help_text='Text for first small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item2_icon',
            field=models.CharField(default='', help_text='Icon for second small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item2_link',
            field=models.ForeignKey(help_text='Link for second small residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item2_text',
            field=models.CharField(default='', help_text='Text for second small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item3_icon',
            field=models.CharField(default='', help_text='Icon for third small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item3_link',
            field=models.ForeignKey(help_text='Link for third small residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item3_text',
            field=models.CharField(default='', help_text='Text for third small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item4_icon',
            field=models.CharField(default='', help_text='Icon for fourth small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item4_link',
            field=models.ForeignKey(help_text='Link for fourth small residents item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='residents_small_item4_text',
            field=models.CharField(default='', help_text='Text for fourth small residents item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_button_text',
            field=models.CharField(default='Visitors', help_text='Text for the visitors button', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item1_image',
            field=models.ForeignKey(help_text='Image for first large visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item1_link',
            field=models.ForeignKey(help_text='Link for first large visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item1_subtext',
            field=models.CharField(default='', help_text='Subtext for first large visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item1_text',
            field=models.CharField(default='', help_text='Text for first large visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item2_image',
            field=models.ForeignKey(help_text='Image for second large visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item2_link',
            field=models.ForeignKey(help_text='Link for second large visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item2_subtext',
            field=models.CharField(default='', help_text='Subtext for second large visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_large_item2_text',
            field=models.CharField(default='', help_text='Text for second large visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item1_icon',
            field=models.CharField(default='', help_text='Icon for first small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item1_link',
            field=models.ForeignKey(help_text='Link for first small visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item1_text',
            field=models.CharField(default='', help_text='Text for first small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item2_icon',
            field=models.CharField(default='', help_text='Icon for second small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item2_link',
            field=models.ForeignKey(help_text='Link for second small visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item2_text',
            field=models.CharField(default='', help_text='Text for second small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item3_icon',
            field=models.CharField(default='', help_text='Icon for third small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item3_link',
            field=models.ForeignKey(help_text='Link for third small visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item3_text',
            field=models.CharField(default='', help_text='Text for third small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item4_icon',
            field=models.CharField(default='', help_text='Icon for fourth small visitors item', max_length=25),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item4_link',
            field=models.ForeignKey(help_text='Link for fourth small visitors item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='visitors_small_item4_text',
            field=models.CharField(default='', help_text='Text for fourth small visitors item', max_length=25),
        ),
    ]
