# Generated by Django 4.2.1 on 2023-07-17 16:33

import common.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_title_emphasis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_buttons',
            field=wagtail.fields.StreamField([('buttons', wagtail.blocks.StructBlock([('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(default='More Details', max_length=50)), ('page', common.blocks.BasePageChooserBlock(required=False))]))), ('button_styles', wagtail.blocks.CharBlock(help_text='Tailwind classes to style the buttons', max_length=150, required=False))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Text to display', required=True))])), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Bold title text for this card. Max length of 100 characters.', max_length=100)), ('text', wagtail.blocks.TextBlock(help_text='Optional text for this card. Max length is 255 characters.', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be automatically cropped to 570px x 370px')), ('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(default='More Details', max_length=50)), ('page', common.blocks.BasePageChooserBlock(required=False))], help_text='Enter a link or select a page'))])))])), ('tabs', wagtail.blocks.StructBlock([('tab_blocks', wagtail.blocks.StreamBlock([('tabs', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='The name of the tab', max_length=50)), ('page_blocks', wagtail.blocks.StreamBlock([('pages', wagtail.blocks.StructBlock([('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(default='More Details', max_length=50)), ('page', common.blocks.BasePageChooserBlock(required=False))])))]))]))]))]))])), ('popular', wagtail.blocks.StructBlock([('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(default='More Details', max_length=50)), ('page', common.blocks.BasePageChooserBlock(required=False))])))])), ('updates', wagtail.blocks.StructBlock([('updates', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='The title of the update', max_length=150)), ('icon', wagtail.blocks.CharBlock(default='fa-regular fa-bell', help_text='The icon associated with this announcement', max_length=50)), ('date', wagtail.blocks.DateBlock(help_text='The date of this announcement')), ('text', wagtail.blocks.RichTextBlock(help_text='A description of the update'))])))]))], use_json_field=True),
        ),
    ]
