# Generated by Django 4.2.3 on 2023-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='byeaster',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bymonth',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bymonthday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='byweekday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='byweekno',
        ),
        migrations.RemoveField(
            model_name='event',
            name='byyearday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interval',
        ),
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.CharField(blank=True, default='', help_text='Apply an RRULE to this event. (Note: Recurring events cannot be featured.)', max_length=255),
        ),
    ]
