# Generated by Django 4.2.1 on 2023-06-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventbase_remove_eventtimespans_event_onetimeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.eventbase')),
                ('start_time', models.DateTimeField(help_text='The date and time when the event begins', null=True)),
                ('end_time', models.DateTimeField(help_text='The date and time when the event ends', null=True)),
                ('featured', models.BooleanField(default=False, help_text='List this event on the featured events page?')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.eventbase',),
        ),
        migrations.RemoveField(
            model_name='onetimeevent',
            name='eventbase_ptr',
        ),
        migrations.AddField(
            model_name='eventbase',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Does this event last all day?'),
        ),
        migrations.DeleteModel(
            name='FeaturedEvent',
        ),
        migrations.DeleteModel(
            name='OneTimeEvent',
        ),
    ]
