#!/bin/bash

#set -o errexit
#set -o pipefail
#set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py clear_wagtail_cache

/usr/local/bin/gunicorn consort.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/app
