# Generated by Django 4.2.1 on 2023-07-14 02:59

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title_emphasis',
            field=models.CharField(default='', help_text="The emphasized part of the banner's title", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_text',
            field=wagtail.fields.RichTextField(help_text='Text under the banner'),
        ),
    ]
