#!/bin/bash

set -xe

# Collect static files
python manage.py collectstatic --noinput

# Migrate the database
python manage.py migrate --noinput

# Start Gunicorn processes
echo Starting Server
python manage.py runserver 0.0.0.0:8000
#gunicorn consort.wsgi:application --bind 0.0.0.0:8000
